### ISSUE TITLE
[ Week 1 ] 1주차 워크북 미션

### ISSUE THREAD

**Issue by Sojeong0430** [DS-UMC-7th/UMC-7th-Iro#1]
### 🛠 Mission

주어진 IA(기획 플로우)와 와이어 프레임(디자인 프로토타입)을 보고 **직접 데이터베이스를 설계**해보기 

### 📝 To-do

- [x] IA 보고 필요한 **엔티티**와 **기능**, 데이터 **요구사항** 파악하기
- [x] 필요한 테이블 작성하기 
- [x] **테이블 간의 관계** 도출하고 설정하기 (외래키 설정 등)
- [x] ERD 툴 사용하여 **시각화**하기

### 🔍 접근 방법

**주어진 IA , 와이어프레임 보고 핵심 기능과 필요한 엔티티 파악하기**
-테이블 마다 들어가야할 칼럼 생각해보기
-기능별 필요한 데이터 고려하기
-기능적인 관점에서 엔티티 간의 관계, 데이터 타입 고려해보기

**테이블 작성하기**
-기본키 타입은 서비스 확장을 고려해 bigint로 설정
-단어 구분은 대소문자가 아닌 밑줄로 구분

**테이블 간의 관계 설정하기**
-기능적 측면에서 고려했던 엔티티 간의 관계를 기반으로 ERD상 연관 관계 설정하기

![image](https://github.com/user-attachments/assets/3e0f1f8b-e8dc-49c2-845b-34f67549d85e)
