### ISSUE TITLE
[ Week 6 ] 6주차 실습 인증

### ISSUE THREAD

**Issue by Sojeong0430** [DS-UMC-7th/UMC-7th-Iro#12]
### 🛠 Mission

QueryDSL 적용하기

### 📝 To-do

- [x] build.gradle 파일에 필요한 플러그인과 종속성 명시
- [x] Q클래스 생성
- [ ] QueryDSL 설정파일 만들기 (JPAQueryFactory Bean 설정)
- [x] QueryDSL 쿼리 작성

### 🔍 접근 방법

호환성 확인
