### ISSUE TITLE
[ Week 2] 2주차 워크북 미션 

### ISSUE THREAD

**Issue by Sojeong0430** [DS-UMC-7th/UMC-7th-Iro#3]
### 🛠 Mission

1주차 때 설계한 데이터베이스를 토대로 아래의 화면에 대한 쿼리를 작성하기

### 📝 To-do

- [x] ERD 보면서 **테이블 간 관계 파악**하기
- [x] 스크린 샷 보면서 **기능 파악**하기
- [x] 주어진 문제 요구 맞추어서 **쿼리 작성**

### 🔍 접근 방법

- ERD통해 **엔티티 간 관계** 파악하기
- 주어진 화면에서 **요구하는 기능**과, 기능에 **필요한 데이터** 파악하기
- SQL 쿼리 작성
