### ISSUE TITLE
[ Week 5 ] 5주차 워크북 미션 

### ISSUE THREAD

**Issue by Sojeong0430** [DS-UMC-7th/UMC-7th-Iro#5]
### 🛠 Mission

 ERD에 해당하는 테이블들에 대한 엔티티 생성 후, 연관 관계 매핑, 칼럼 세부 설정 적용하기

### 📝 To-do

- [x] ERD 확인하고 필요한 엔티티와 엔티티간 관계 파악하기
- [x] 엔티티 클래스 생성하기
- [x] 연관 관계 매핑하기
- [x] 칼럼 세부 설정 적용하기
- [x] 테스트 후 테이블 생성된것 확인하기

### 🔍 접근 방법

- 테이블의 목적과 기능을 생각하며 양방향 매핑이 필요한 경우를 잘 고려하여 연관 관계를 설정한다.
- 칼럼의 세부 설정이 필요한 경우를 고려하여 설정해준다
- !같은 프로젝트 파일로 이후 주차 미션 진행하다가 기존 파일에 문제가 생겨 삭제 후 아예 프로젝트를 새로 생성해서 다시 PR 했습니다!
