### ISSUE TITLE
[ Week 6 ] 6주차 워크북 실습인증

### ISSUE THREAD

**Issue by Sojeong0430** [DS-UMC-7th/UMC-7th-Iro#7]
### 🛠 Mission

QueryDSL 적용하기 실습 코드 첨부

### 📝 To-do

- [x] build.gradle 파일에 필요한 플러그인과 종속성 명시
- [x] Q 클래스 생성
- [x] QueryDSL 설정파일 만들기 (JPAQueryFactory Bean 설정)
- [x] QueryDSL 쿼리 작성
